name: adaptive_sph_binder
channels:
- conda-forge
- defaults
dependencies:
  - python>=3.8
  - setuptools>=42.0.0
  - Cython
  - numpy
  - matplotlib
  - mako
  - h5py
  - pandas
  - Beaker
  - cyarray
  - pip
  - pip:
      - https://github.com/pypr/compyle/zipball/master
      - https://github.com/pypr/pysph/zipball/master
